# Generated by Django 5.1.6 on 2025-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_situr', models.CharField(max_length=20, unique=True)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_consejo_comunal', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'comuna',
                'ordering': ['id_comuna'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsejoComunal',
            fields=[
                ('id_consejo_comunal', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_situr', models.CharField(max_length=20, unique=True)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'consejo_comunal',
                'ordering': ['id_consejo_comunal'],
                'managed': False,
            },
        ),
    ]
