# Generated by Django 5.1.6 on 2025-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosBasicos',
            fields=[
                ('id_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('agua', models.BooleanField()),
                ('electricidad', models.BooleanField()),
                ('gas', models.BooleanField()),
                ('internet', models.BooleanField()),
                ('aseo', models.BooleanField()),
                ('cloaca', models.BooleanField()),
            ],
            options={
                'db_table': 'servicios_basicos',
                'ordering': ['id_servicios'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SituacionVivienda',
            fields=[
                ('id_situacion_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'situacion_vivienda',
                'ordering': ['id_situacion_vivienda'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_area', models.CharField(max_length=5)),
                ('numero', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'telefono',
                'ordering': ['id_vivienda'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoOcupacionVivienda',
            fields=[
                ('id_tipo_ocupacion', models.AutoField(primary_key=True, serialize=False)),
                ('vivienda_ocupada', models.BooleanField()),
                ('subtipo_ocupacion', models.CharField(max_length=35)),
                ('tiene_documentacion', models.BooleanField()),
                ('respuesta_otro', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_ocupacion_vivienda',
                'ordering': ['id_tipo_ocupacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPared',
            fields=[
                ('id_tipo_pared', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_pared',
                'ordering': ['id_tipo_pared'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPiso',
            fields=[
                ('id_tipo_piso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_piso',
                'ordering': ['id_tipo_piso'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTecho',
            fields=[
                ('id_tipo_techo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_techo',
                'ordering': ['id_tipo_techo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id_tipo_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_vivienda',
                'ordering': ['id_tipo_vivienda'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('numero_vivienda', models.CharField(max_length=20)),
                ('cantidad_habitantes', models.IntegerField()),
                ('cantidad_familias', models.IntegerField()),
                ('cantidad_banos', models.IntegerField()),
                ('cantidad_cuartos', models.IntegerField()),
            ],
            options={
                'db_table': 'vivienda',
                'ordering': ['id_vivienda'],
                'managed': False,
            },
        ),
    ]
