# Generated by Django 5.1.6 on 2025-04-23 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id_celular', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_operadora', models.CharField(max_length=5)),
                ('numero', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'celular',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorreoElectronico',
            fields=[
                ('id_correo', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'correo_electronico',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'estado_civil',
                'ordering': ['id_estado_civil'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id_etnia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'etnia',
                'ordering': ['id_etnia'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id_habitante', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
                ('discapacidad', models.BooleanField()),
                ('pertenece_etnia', models.BooleanField()),
            ],
            options={
                'db_table': 'habitante',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id_nacionalidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'db_table': 'nacionalidad',
                'ordering': ['id_nacionalidad'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelEstudio',
            fields=[
                ('id_nivel_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'nivel_estudio',
                'ordering': ['id_nivel_estudio'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaisOrigen',
            fields=[
                ('id_pais_origen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'pais_origen',
                'ordering': ['id_pais_origen'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('id_tipo_discapacidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_discapacidad',
                'ordering': ['id_tipo_discapacidad'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id_tipo_sangre', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_sangre',
                'ordering': ['id_tipo_sangre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitanteDiscapacidad',
            fields=[
                ('id_habitante', models.OneToOneField(db_column='id_habitante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DatosHabitante.habitante')),
            ],
            options={
                'db_table': 'habitante_discapacidad',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitanteEstadoCivil',
            fields=[
                ('id_habitante', models.OneToOneField(db_column='id_habitante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DatosHabitante.habitante')),
            ],
            options={
                'db_table': 'habitante_estado_civil',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitanteEtnia',
            fields=[
                ('id_habitante', models.OneToOneField(db_column='id_habitante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DatosHabitante.habitante')),
            ],
            options={
                'db_table': 'habitante_etnia',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitanteNivelEstudio',
            fields=[
                ('id_habitante', models.OneToOneField(db_column='id_habitante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DatosHabitante.habitante')),
            ],
            options={
                'db_table': 'habitante_nivel_estudio',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HabitanteTipoSangre',
            fields=[
                ('id_habitante', models.OneToOneField(db_column='id_habitante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DatosHabitante.habitante')),
            ],
            options={
                'db_table': 'habitante_tipo_sangre',
                'ordering': ['id_habitante'],
                'managed': False,
            },
        ),
    ]
