# Generated by Django 5.1.6 on 2025-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbitoTerritorial',
            fields=[
                ('id_ambito_territorial', models.AutoField(primary_key=True, serialize=False)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'ambito_territorial',
                'ordering': ['id_ambito_territorial'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_parroquia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parroquia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ubicacion',
                'ordering': ['id_ubicacion'],
                'managed': False,
            },
        ),
    ]
